<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'first_name' => 'Test',
                'last_name' => 'User',
                'email' => 'test@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'role' => 'admin',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 1, 
            ],
            [
                'first_name' => 'John',
                'last_name' => 'Dorksils',
                'email' => 'jdd@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Accountant',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 5, 
            ],
            [
                'first_name' => 'Ahmed',
                'last_name' => 'Jinadh',
                'email' => 'AJ@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Engineer',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 2, 
            ],
            [
                'first_name' => 'Hassan',
                'last_name' => 'Saeedh',
                'email' => 'HHS@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Engineer',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 2, 
            ],
            //15 additonal
            [
                'first_name' => 'Tim',
                'last_name' => 'Burt',
                'email' => 'Timburt@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Salesman',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 4, 
            ],
            [
                'first_name' => 'Mary',
                'last_name' => 'Rhodes',
                'email' => 'MRhodes@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Engineer',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 2, 
            ],
            [
                'first_name' => 'Ashley',
                'last_name' => 'Baker',
                'email' => 'ABBaker@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'HR Agent',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 1, 
            ],
            [
                'first_name' => 'Graham',
                'last_name' => 'Aker',
                'email' => 'Mrbushido@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Manager',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 4, 
            ],
            [
                'first_name' => 'Kiryu',
                'last_name' => 'Kazuma',
                'email' => 'kkslider@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Admin',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 1, 
            ],
            [
                'first_name' => 'Ahmed',
                'last_name' => 'Basheer',
                'email' => 'Batte@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Sales Agent',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 3, 
            ],
            [
                'first_name' => 'Emma',
                'last_name' => 'Watson',
                'email' => 'ewatson@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Software Engineer',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 2,
            ],
            [
                'first_name' => 'Oliver',
                'last_name' => 'Black',
                'email' => 'oblack@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Data Analyst',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 5,
            ],
            [
                'first_name' => 'Ava',
                'last_name' => 'Thompson',
                'email' => 'athompson@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Marketing Specialist',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 4,
            ],
            [
                'first_name' => 'Liam',
                'last_name' => 'Davies',
                'email' => 'liam.davies@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'HR Manager',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 1,
            ],
            [
                'first_name' => 'Sophia',
                'last_name' => 'Jackson',
                'email' => 'sophia.jackson@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Product Manager',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 3,
            ],
            [
                'first_name' => 'Jacob',
                'last_name' => 'Mason',
                'email' => 'jacob.mason@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Project Coordinator',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 4,
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Green',
                'email' => 'emily.green@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'Operations Manager',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
                'department_id' => 1,
            ]
        ]);
    }
}
